<?php
if ( ! defined( 'ABSPATH' ) ) exit;

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b3e3f65c0bf6',
	'title' => 'Module Class Mapping',
	'fields' => array(
		array(
			'key' => 'field_5b3e3f6dd28a0',
			'label' => 'Modules',
			'name' => 'class_map_modules',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add a Module to Apply Class Maps to',
			'sub_fields' => array(
				array(
					'key' => 'field_5b3e3f90d28a1',
					'label' => 'Module Type',
					'name' => 'module_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'all' => 'All',
						'accordion' => 'accordion',
						'alternating' => 'alternating',
						'generic_content' => 'generic_content',
						'media' => 'media',
						'multi' => 'multi',
						'posts-slider' => 'posts-slider',
						'slider' => 'slider',
						'table' => 'table',
						'three-column-image-grid' => 'three-column-image-grid',
						'three_col' => 'three_col',
						'woo_table' => 'woo_table',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b3f96b35cf4d',
					'label' => 'Class Groups',
					'name' => 'class_groups',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add a Class Group (Like Font, Background, etc)',
					'sub_fields' => array(
						array(
							'key' => 'field_5b3f96dd5cf4f',
							'label' => 'Group Name',
							'name' => 'group_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b3f96f95cf50',
							'label' => 'Allow Multiple Choices',
							'name' => 'allow_multiple_choices',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5b3f97135cf51',
							'label' => 'Class Maps',
							'name' => 'class_maps',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add a Class Map',
							'sub_fields' => array(
								array(
									'key' => 'field_5b3f9795686f5',
									'label' => 'Class Selector (ie, "class-one")',
									'name' => 'selector',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b3f97aa686f6',
									'label' => 'Class Name',
									'name' => 'class_name',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'global-modules',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;